version: '3.3'

services:
  backend:
    container_name: restapi-java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - pusak-net

networks:
  pusak-net:
    driver: bridge
