version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restapi-java
    ports:
      - "8080:8080"
    networks:
      - pusak-net

networks:
  pusak-net:
    driver: bridge
